module.exports = {
  apps: [
    {
      name: 'scanner',
      script: 'dist/src/scanner/scanner.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      cwd: './',
      env: {
        NODE_ENV: 'production',
        BOT_TYPE: 'scanner',
      },
      error_file: 'logs/scanner-err.log',
      out_file: 'logs/scanner-out.log',
      merge_logs: true,
      time: true,
    },
    {
      name: 'spot-trader',
      script: 'dist/src/spot/launcher-spot.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      cwd: './',
      env: {
        NODE_ENV: 'production',
        BOT_TYPE: 'spot',
        SIGNAL_FILE: './signals/spot-signals.json',
        STATE_FILE: './data/bot-state.json',
      },
      error_file: 'logs/spot-err.log',
      out_file: 'logs/spot-out.log',
      merge_logs: true,
      time: true,
    },
    {
      name: 'futures-trader-1',
      script: 'dist/src/futures/launcher-future.js', // or bf.js
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      cwd: './',
      env: {
        NODE_ENV: 'production',
        BOT_TYPE: 'futures',
        BOT_INSTANCE: 'futures-1',
        SIGNAL_FILE: './signals/futures-signals.json',
        STATE_FILE: './states/futures-state.json',
      },
      error_file: 'logs/futures-err.log',
      out_file: 'logs/futures-out.log',
      merge_logs: true,
      time: true,
    },
    {
      name: 'futures-trader-2',
      script: 'dist/src/test/launcher-future-legacy.js', // or bf.js
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      cwd: './',
      env: {
        NODE_ENV: 'production',
        BOT_TYPE: 'futures',
        BOT_INSTANCE: 'futures-legacy',
        SIGNAL_FILE: './signals/futures-legacy-signals.json',
        STATE_FILE: './states/futures-legacy-state.json',
      },
      error_file: 'logs/futures-legacy-err.log',
      out_file: 'logs/futures-legacy-out.log',
      merge_logs: true,
      time: true,
    },
  ],
};
