export const MSCI_LARGE_CUP = [
  'BTC/USDT',
  'ETH/USDT',
  'BNB/USDT',
  'SOL/USDT',
  'XRP/USDT',
  'ADA/USDT',
  'DOGE/USDT',
  'TRX/USDT',
  'TON/USDT',
  'UNI/USDT',
  'LINK/USDT',
  'LTC/USDT',
  'BCH/USDT',
];

export const MSCI_MID_CUP = [
  // 'APT/USDT',
  'ARB/USDT',
  'ATOM/USDT',
  // 'AVAX/USDT',
  'DOT/USDT',
  'MYX/USDT',
  'NEAR/USDT',
  'M/USDT',
  // 'DCR/USDT',
  // 'ICP/USDT',
  // 'INJ/USDT',
  'LIT/USDT',
  'IMX/USDT',
  'SUI/USDT',
  'SEI/USDT',
  'STX/USDT',
  'TIA/USDT',
  'TAO/USDT',
  'RUNE/USDT',
  // 'RENDER/USDT',
  'QNT/USDT',
  'PAXG/USDT',
  'OP/USDT',
  // 'FIL/USDT',
  'HBAR/USDT',
  'VET/USDT',
  // 'UNI/USDT',
  'AAVE/USDT',
  // 'OP/USDT',
  // 'ARBITRUM/USDT',
  'ONDO/USDT',
  // 'PENDLE/USDT',
  // 'IP/USDT',
];

export const MSCI_SMALL_CUP = [
  'GALA/USDT',
  'CRV/USDT',
  // 'AXS/USDT',
  'SAND/USDT',
  'MANA/USDT',
  'CHZ/USDT',
  'JASMY/USDT',
  'GRT/USDT',
  'ICP/USDT',
  'IMX/USDT',
  'INJ/USDT',
  'LPT/USDT',
  'JST/USDT',
  'JOE/USDT',
  // 'LDO/USDT',
  'ENA/USDT',
  'ETHFI/USDT',
  'PYTH/USDT',
  'JUP/USDT',
  'KAITO/USDT',
  'KAIA/USDT',
  'MASK/USDT',
  'WLD/USDT',
  'WOO/USDT',
  'ZK/USDT',
  // 'STRK/USDT',
  // 'DASH/USDT',
  'ZEC/USDT',
  'XLM/USDT',
  'XTZ/USDT',
  'ZEN/USDT',
  'XRP/USDT',
  'XPL/USDT',
  // 'VIRTUAL/USDT',
  'WIF/USDT',
  'XMR/USDT',
  'TST/USDT',
  'TUT/USDT',
  'UNI/USDT',
  'VET/USDT',
  // 'SENT/USDT',
  'SKY/USDT',
  'SOMI/USDT',
  'SYRUP/USDT',
  'SUN/USDT',
  'ONT/USDT',
  'RIF/USDT',
  'RED/USDT',
  'FARTCOIN/USDT',
  'FET/USDT',
  'FLUID/USDT',
  'DUSK/USDT',
  'G/USDT',
  'GLM/USDT',
  'GTC/USDT',
  'HYPE/USDT',
  'ICNT/USDT',
  'IOTA/USDT',
  'KAIA/USDT',
  'M/USDT',
  // 'MORPHO/USDT',
  'MEME/USDT',
  'MBOX/USDT',
  'MEW/USDT',
  'NEXO/USDT',
  'NIGHT/USDT',
  'NOT/USDT',
  'PENGU/USDT',
  // 'PIPPIN/USDT',
  'PLAY/USDT',
  'PIEVERSE/USDT',
  'PROM/USDT',
  'POL/USDT',
  '2Z/USDT',
  'XEC/USDT',
  'LUNC/USDT',
  'ARB/USDT',
  'AERO/USDT',
  'AXS/USDT',
  'BCH/USDT',
  'BEAT/USDT',
  'BREV/USDT',
  'BSV/USDT',
  'BULLA/USDT',
  'CAKE/USDT',
  'CC/USDT',
  'CYS/USDT',
];

export const MSCI_TINY_CUP = [
  'API3/USDT',
  'ALGO/USDT',
  // 'ATOM/USDT',
  'SHIB/USDT',
  // 'FLOKI/USDT',
  // 'BTT/USDT',
  'BEAMX/USDT',
  'BONK/USDT',
  // 'GNO/USDT',
  'PEPE/USDT',
  'FET/USDT',
  'FLUID/USDT',
  'FOGO/USDT',
  'GIGGLE/USDT',
  'GRT/USDT',
  'JTO/USDT',
  'MANTA/USDT',
  'MELANIA/USDT',
  'SSV/USDT',
  'WLFI/USDT',
  'ZBT/USDT',
  'ZKP/USDT',
  // 'FARTCOIN/USDT',
  'TRUMP/USDT',
  'SATS/USDT',
  'COW/USDT',
  // 'MEME/USDT',
  'KITE/USDT',
  'MEW/USDT',
  'RATS/USDT',
  'PENGU/USDT',
  'WIF/USDT',
  'WCT/USDT',
  'BROCCOLI714/USDT',
  'THETA/USDT',
  '币安人生/USDT',
  'ASTER/USDT',
  'DODO/USDT',
  'ETHFI/USDT',
  'SAND/USDT',
  'CHESS/USDT',
  'GPS/USDT',
  'NKN/USDT',
  'JUV/USDT',
  'ZKP/USDT',
  'ALLO/USDT',
];

export const TOKEN = [
  ...MSCI_LARGE_CUP,
  ...MSCI_MID_CUP,
  ...MSCI_SMALL_CUP,
  ...MSCI_TINY_CUP,
];

// const MSCI_TINY_CUP = [
//   'ALGO/USDT',
//   'SHIB/USDT',
//   'FLOKI/USDT',
//   'ASTER/USDT',
//   'BROCCOLI714/USDT',
//   'BTT/USDT',
//   'DODO/USDT',
//   'ETHFI/USDT',
//   'GIGGLE/USDT',
//   'GRT/USDT',
//   'JTO/USDT',
//   'MANTA/USDT',
//   'MELANIA/USDT',
//   'SATS/USDT',
//   'SAND/USDT',
//   'SSV/USDT',
//   'THETA/USDT',
//   'TRUMP/USDT',
//   'WLFI/USDT',
//   'ZBT/USDT',
//   'ZKP/USDT',
//   '币安人生/USDT',
// ];

export const SYMBOLS = [
  '2Z/USDT',
  'API3/USDT',
  'XEC/USDT',
  'LUNC/USDT',
  'PEPE/USDT',
  'AAVE/USDT',
  'ADA/USDT',
  'ANIME/USDT',
  'AIN/USDT',
  'ALGO/USDT',
  'APT/USDT',
  'ARB/USDT',
  'ASTER/USDT',
  'ATOM/USDT',
  'AERO/USDT',
  'AVAX/USDT',
  'AXS/USDT',
  'BCH/USDT',
  'BEAT/USDT',
  'BREV/USDT',
  'BROCCOLI714/USDT',
  'BTC/USDT',
  'BTT/USDT',
  'BNB/USDT',
  'BONK/USDT',
  'BSV/USDT',
  'BULLA/USDT',
  'CAKE/USDT',
  'CC/USDT',
  'CHZ/USDT',
  'CRV/USDT',
  'CYS/USDT',
  // 'DCR/USDT',
  'ENA/USDT',
  'ETH/USDT',
  'FARTCOIN/USDT',
  'FET/USDT',
  'FIL/USDT',
  'FLUID/USDT',
  'FOGO/USDT',
  'DASH/USDT',
  'DEGO/USDT',
  'DENT/USDT',
  'DOGE/USDT',
  'DODO/USDT',
  'DOT/USDT',
  'DUSK/USDT',
  'G/USDT',
  'GALA/USDT',
  'GALA/USDT',
  'GIGGLE/USDT',
  'GLM/USDT',
  'GRT/USDT',
  'GTC/USDT',
  'HYPE/USDT',
  'HBAR/USDT',
  'ICP/USDT',
  'ICNT/USDT',
  'IMX/USDT',
  'INJ/USDT',
  'IP/USDT',
  'IOTA/USDT',
  'JASMY/USDT',
  'JST/USDT',
  'JOE/USDT',
  'JTO/USDT',
  'JUP/USDT',
  'KAIA/USDT',
  'LIT/USDT',
  'LPT/USDT',
  'LTC/USDT',
  'LDO/USDT',
  'LINK/USDT',
  'M/USDT',
  'MASK/USDT',
  'MORPHO/USDT',
  'MEME/USDT',
  'MBOX/USDT',
  'MEW/USDT',
  'MELANIA/USDT',
  'MYX/USDT',
  'NAORIS/USDT',
  'NEXO/USDT',
  'NEAR/USDT',
  'NIGHT/USDT',
  'NOT/USDT',
  'ONDO/USDT',
  'OP/USDT',
  'PAXG/USDT',
  'PENGU/USDT',
  'PIPPIN/USDT',
  'PHB/USDT',
  'PLAY/USDT',
  'PENDLE/USDT',
  'PIEVERSE/USDT',
  'PROM/USDT',
  'POL/USDT',
  'POLYX/USDT',
  'PUMP/USDT',
  'PYTH/USDT',
  'ONT/USDT',
  'QNT/USDT',
  'SUI/USDT',
  'RATS/USDT',
  'RIF/USDT',
  'RENDER/USDT',
  'RUNE/USDT',
  'RED/USDT',
  'SAND/USDT',
  'SATS/USDT',
  'SEI/USDT',
  'SENT/USDT',
  'SIREN/USDT',
  'SKY/USDT',
  'SOL/USDT',
  'SOMI/USDT',
  'STX/USDT',
  'SSV/USDT',
  'STRK/USDT',
  'SYRUP/USDT',
  'SUN/USDT',
  'TAO/USDT',
  'THETA/USDT',
  'TIA/USDT',
  'TST/USDT',
  'TRX/USDT',
  'TRUMP/USDT',
  'TRIA/USDT',
  'TUT/USDT',
  'TON/USDT',
  'UNI/USDT',
  'VANRY/USDT',
  'VET/USDT',
  'VIRTUAL/USDT',
  'VVV/USDT',
  'WCT/USDT',
  'WLFI/USDT',
  'WLD/USDT',
  'WIF/USDT',
  'WOO/USDT',
  'XMR/USDT',
  'XRP/USDT',
  'XTZ/USDT',
  'XPL/USDT',
  'XLM/USDT',
  'ZBT/USDT',
  'ZKP/USDT',
  'ZEC/USDT',
  'ZEN/USDT',
  'ZK/USDT',
  '龙虾/USDT',
  '币安人生/USDT',
];

// export const YOUR_SYMBOLS = [
//   'AAVE/USDT',
//   'ADA/USDT',
//   'APT/USDT',
//   'ARB/USDT',
//   'ATOM/USDT',
//   'AVAX/USDT',
//   'AXS/USDT',
//   'BCH/USDT',
//   'BTC/USDT',
//   'BNB/USDT',
//   'CAKE/USDT',
//   'CHZ/USDT',
//   'CRV/USDT',
//   'DOGE/USDT',
//   'DOT/USDT',
//   'ETH/USDT',
//   'FET/USDT',
//   'FIL/USDT',
//   'GALA/USDT',
//   'HBAR/USDT',
//   'ICP/USDT',
//   'IMX/USDT',
//   'INJ/USDT',
//   'JASMY/USDT',
//   'JUP/USDT',
//   'LINK/USDT',
//   'LTC/USDT',
//   'LDO/USDT',
//   'NEAR/USDT',
//   'OP/USDT',
//   'PAXG/USDT',
//   'PENDLE/USDT',
//   'PYTH/USDT',
//   'QNT/USDT',
//   'RENDER/USDT',
//   'RUNE/USDT',
//   'SEI/USDT',
//   'SOL/USDT',
//   'STX/USDT',
//   'STRK/USDT',
//   'SUI/USDT',
//   'TON/USDT',
//   'TRX/USDT',
//   'UNI/USDT',
//   'VET/USDT',
//   'WLD/USDT',
//   'XMR/USDT',
//   'XRP/USDT',
//   'XTZ/USDT',
//   'XLM/USDT',
// ];
